spring.application.name=ITSS-NIHONGO

# Database Configuration
#spring.datasource.url= jdbc:postgresql://localhost:5432/Itss
#spring.datasource.username= postgres
#spring.datasource.password= 1

spring.datasource.url= jdbc:postgresql://14.162.146.23:5432/ITSS
spring.datasource.username= root
spring.datasource.password= root@2025
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Configuration
server.port=8081

# JWT Security Configuration
application.security.jwt.secret-key=b6a4f2319dbde50cf2a1e476ec9f77e3d8c22148790c4e537103c0f77e3a6c42
application.security.jwt.expiration=1209600000

# Cloudinary Configuration
cloudinary.cloud-name=dcxazccv9
cloudinary.api-key=653231966393724
cloudinary.api-secret=9ei8iWPUmskz1Mj8JNHXlXmxxHs